/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_steamoverlay_OpenSteamClient_OpenSteamClient */

#ifndef _Included_com_example_steamoverlay_OpenSteamClient_OpenSteamClient
#define _Included_com_example_steamoverlay_OpenSteamClient_OpenSteamClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_steamoverlay_OpenSteamClient_OpenSteamClient
 * Method:    logIn
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_steamoverlay_OpenSteamClient_OpenSteamClient_logIn
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_example_steamoverlay_OpenSteamClient_OpenSteamClient
 * Method:    logout
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_steamoverlay_OpenSteamClient_OpenSteamClient_logout
  (JNIEnv *, jobject);

/*
 * Class:     com_example_steamoverlay_OpenSteamClient_OpenSteamClient
 * Method:    startEventLoop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_steamoverlay_OpenSteamClient_OpenSteamClient_startEventLoop
  (JNIEnv *, jobject);

/*
 * Class:     com_example_steamoverlay_OpenSteamClient_OpenSteamClient
 * Method:    pollMessages
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_steamoverlay_OpenSteamClient_OpenSteamClient_pollMessages
  (JNIEnv *, jobject);

/*
 * Class:     com_example_steamoverlay_OpenSteamClient_OpenSteamClient
 * Method:    constructNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_steamoverlay_OpenSteamClient_OpenSteamClient_constructNative
  (JNIEnv *, jobject);

/*
 * Class:     com_example_steamoverlay_OpenSteamClient_OpenSteamClient
 * Method:    destructNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_steamoverlay_OpenSteamClient_OpenSteamClient_destructNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
